### ISSUE TITLE
console log message can't be disabled

### ISSUE THREAD

**Issue by danielb2** [lucastheisen/saxtract#1]
https://github.com/lucastheisen/saxtract/blob/master/saxtract.js#L41

debugging left by accident?

**Comment by lucastheisen** [comment]
A code fix has been committed.  Logging is _now_ disabled by default, and you can enable it using:

``` javascript
saxtract.logging = true;
```

I am working on getting `npm publish` to work.  Hopefully will be on the repo soon.

**Comment by danielb2** [comment]
awesome. thanks for the quick action :+1:

**Comment by lucastheisen** [comment]
Version 0.0.4 published: https://www.npmjs.com/package/saxtract

**Comment by danielb2** [comment]
Have you considered using semver? http://semver.org/

**Comment by lucastheisen** [comment]
Yeah, I do use it, but find 0 to be a perfectly valid version number :).  I could easily be persuaded to re-release as 1.0.0 if you would like...  Let me know.

**Comment by danielb2** [comment]
> How do I know when to release 1.0.0?
> 
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by lucastheisen** [comment]
Yeah, read that...  This is hobby code.  Don't really have a production :)

**Comment by danielb2** [comment]
I'm looking at putting it in production. Should I look for a different library?

**Comment by danielb2** [comment]
This library is the _only_ one I found which allows for a spec to be passed into XML, which is the only reliable way of converting XML to JSON. Do you know of any others?

**Comment by lucastheisen** [comment]
This is stable.  I have been using it for years.  Just no _production_.  I have my own personal site that consumes an XML rest api.  Also, at the time I originally wrote it, node itself was at version 0.8.4...  It's got some good unit tests to show what is capable of, and is be happy to accept any pull requests you might have.  I also [ported it to perl](https://github.com/lucastheisen/saxtract-perl), so I clearly like the concept.

**Comment by danielb2** [comment]
Excellent :)   Since it's public, and to follow semver, I'm suggesting 1.0.0 then.

**Comment by lucastheisen** [comment]
Done!  v1.0.0 has been released.  Enjoy, and feel free to contribute.

**Comment by danielb2** [comment]
excellent. This is a nice library ;)  I'm glad I found it
