### ISSUE TITLE
trailing spaces are stripped

### ISSUE THREAD

**Issue by danielb2** [lucastheisen/saxtract#2]
I'm reading in XML from some HTML that's got trailing spaces, and those are lost in translation. However, the trailing spaces are part of a key for POST request (an error upstream I have no control over) and saxtract is dropping it as illustrated in the code below:

``` javascript
var Saxtract = require('saxtract');
var xml = '<xml><option value=\'foo \'>foo </option></xml>';

var saxed = Saxtract.parse(xml, {
    '/xml/option': { name: 'options', type: 'array' }
});
```

**Expected result:**

``` javascript
{ options: [ 'foo ' ] }
```

**Actual result:**

``` javascript
{ options: [ 'foo' ] }
```

Looks like the related code is here: 

https://github.com/lucastheisen/saxtract/blob/master/saxtract.js#L109

**Comment by lucastheisen** [comment]
Fixed in version 1.0.1.  I added a new config for preserving white space either at an instance level, or per call to parse (as an additional argument).  See the README for more details.
